### ISSUE TITLE
lzma_check compile issue

### ISSUE THREAD

**Issue by tynewydd** [nmoinvaz/minizip#325]
Compiling for the first time with cmake - for lib/liblzma/check/check.c:13 I get check.h:115:54: error: unknown type name 'lzma_check'
extern void lzma_check_init(lzma_check_state *check, lzma_check type); 

and so on every time lzma_check is mentioned in check.h.

This seems to be because the typedef for lzma_check is in ../api/lzma/check.h but not in ../check/check.h

**Comment by nmoinvaz** [comment]
Can you provide a pull request. I'm not able to reproduce.

**Comment by tynewydd** [comment]
Ignore please - the issue is something about the cmake environment I added it to as a subdirectory. When built on its own it compiles OK.
