### ISSUE TITLE
Build failure on OS X ≤ 10.9 due to missing CommonCrypto/CommonRandom.h

### ISSUE THREAD

**Issue by ryandesign** [nmoinvaz/minizip#384]
Hi,

Just wanted to let you know that minizip 2.8.6 fails to build on OS X 10.9 and earlier because:

```
mz_crypt_apple.c:19:10: fatal error: 'CommonCrypto/CommonRandom.h' file not found
#include <CommonCrypto/CommonRandom.h>
         ^
```

Here are build failure logs for OS X [10.7](https://build.macports.org/builders/ports-10.7_x86_64_legacy-builder/builds/101165/steps/install-port/logs/stdio), [10.8](https://build.macports.org/builders/ports-10.8_x86_64_legacy-builder/builds/93355/steps/install-port/logs/stdio), and [10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/87769/steps/install-port/logs/stdio).

It [builds fine on OS X 10.10](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/85843/steps/install-port/logs/stdio) and later.

**Comment by nmoinvaz** [comment]
You can build instead using the Brian's Gladman's library -DMZ_BRG=ON or OpenSSL instead -DMZ_OPENSSL=ON

**Comment by Coeur** [comment]
Note that if you're coming from the branch 1.2, then it was historically using BRG (Brian's Gladman's AES lib).

**Comment by nmoinvaz** [comment]
I have added a check to the cmake in the `dev` branch that will check for the availablity of common crypto library.

**Comment by ryandesign** [comment]
> You can build instead using the Brian's Gladman's library -DMZ_BRG=ON or OpenSSL instead -DMZ_OPENSSL=ON

Thanks, I'll look into those.


> I have added a check to the cmake in the `dev` branch that will check for the availablity of common crypto library.

Thanks, but it looks like you added a check for Common*Crypto*.h, but the header you're using that's missing is Common*Random*.h.

The first appearance of some of the Common Crypto functions was Mac OS X 10.4. The CommonCrypto.h header (which just includes some of the others) was added in OS X 10.8. The CommonRandom.h header (which contains the `CCRandomGenerateBytes` function minizip is using) was added in OS X 10.10.

**Comment by nmoinvaz** [comment]
Ok, I have updated it again. Thank you.

**Comment by nmoinvaz** [comment]
I'm not sure if it makes sense to use `SecRandomCopyBytes` instead. @Coeur thoughts?

**Comment by nmoinvaz** [comment]
I have changed it to use `SecRandomCopyBytes` which is available on 10.7. I wouldn't be surprised if underneath `CCRandomCopyBytes` it uses this function. Let me know if you have any issues with this.

**Comment by Coeur** [comment]
> I'm not sure if it makes sense to use `SecRandomCopyBytes` instead. @Coeur thoughts?

Regarding CommonCrypto.h, in my projects, I only target macOS 10.8+ for "modern" Objective-C or macOS 10.14.3+ for Swift with stable ABI, so I always have that header.

Regarding CCRandomCopyBytes, it's partially open source: https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60074/lib/CommonRandom.c
It does:
```objective-c
rng = ccDRBGGetRngState();
return ccrng_generate((struct ccrng_state *)(struct ccrng_CommonCrypto_state *)rng, count, bytes);
```

So it has the same signature as [SecRandomCopyBytes](https://developer.apple.com/documentation/security/1399291-secrandomcopybytes?language=objc), and yes, they are probably interchangeable.

And for the laugh, CommonCrypto is using Brian Gladman AES under the hood: https://opensource.apple.com/source/CommonCrypto/CommonCrypto-55010/Source/GladmanAES/

**Comment by nmoinvaz** [comment]
> And for the laugh, CommonCrypto is using Brian Gladman AES under the hood: https://opensource.apple.com/source/CommonCrypto/CommonCrypto-55010/Source/GladmanAES/

Haha that is a good laugh! It looks like more recent versions might not use it, still funny though.
