### PR TITLE
mz.h: fix build with gcc 4.8

### LINKED ISSUE #510: Compilation Problem
An error occurred  When I tried to run cmake in the minizip directory.
/minizip-master/mz.h:162:44: error: missing binary operator before token "("
    (defined(__has_include) && __has_include(<stdint.h>))
                                            ^
/minizip-master/mz_crypt.c:109:51: error: unknown type name ‘uint8_t’
     int32_t salt_length, int32_t iteration_count, uint8_t *key, int32_t key_length) {
                                                   ^
make[2]: *** [CMakeFiles/minizip.dir/mz_crypt.c.o] Error 1
make[1]: *** [CMakeFiles/minizip.dir/all] Error 2
make: *** [all] Error 2

Any idea on how to resolve this problem?

### PR DESCRIPTION
**Pull request by ffontaine**
gcc 4.8 does not support __has_include directive as a result the build
will fail on:

```
/home/naourr/work/instance-1/output-1/build/minizip-2.10.0/mz.h:162:44: error: missing binary operator before token "("
    (defined(__has_include) && __has_include(<stdint.h>))
                                            ^
```

Fix it by appling:
https://gcc.gnu.org/onlinedocs/gcc-10.1.0/cpp/_005f_005fhas_005finclude.html

Fix #510

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Merged to `dev` branch thank you!
